# ===============================
# Import Files
# ===============================
spring.config.import=file:credentials.properties



# ===============================
# Application Info
# ===============================
spring.application.name=connector-service
server.port=${SERVER.PORT}

# ===============================
# Eureka Client Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true